//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SvcMFCUI.rc
//
#define IDC_SAVE                        2
#define IDC_EDITTITLE                   1000
#define IDR_MENUVPTLine                 1003
#define IDI_VPTLine                     1005
#define IDI_ANNOT1                      1006
#define IDB_BLOCKLINE                   1008
#define IDB_FILMHOLES                   1009
#define IDC_CURSOR2                     1012
#define IDC_HANDZOOM                    1013
#define IDC_HANDDN                      1014
#define IDD_EDITTITLE                   1015
#define IDC_LIST1                       2000
#define IDD_PROFILING                   2000
#define IDC_LIST                        2000
#define IDD_PROGRESS                    2001
#define IDC_PROGRESS                    2002
#define IDD_DLGLOG                      2002
#define IDC_PERCENT                     2003
#define IDD_DLGDUMMY                    2003
#define IDC_MESSAGE                     2004
#define IDC_FPS                         2005
#define IDD_SETUPPARAMS                 2005
#define IDB_LOGIMG                      2006
#define IDD_CAPTEURS                    2007
#define IDD_SLAVES                      2008
#define IDC_MBRGAP                      2009
#define IDR_MAINFRAME                   2009
#define IDC_SPRITESCALE                 2010
#define IDC_MINSPRITESCALE              2011
#define IDC_MAXSPRITES                  2012
#define IDR_LOGWND                      2012
#define IDC_BUMPMAP                     2013
#define IDR_PROFILEWND                  2013
#define IDC_CUBEMAP                     2014
#define IDC_LIGHTDIRAL                  2015
#define IDR_OPENGLWND                   2015
#define IDC_LIGHTEXP                    2016
#define IDD_LOG                         2016
#define IDC_BUMPFACT                    2017
#define IDD_CONSOLE                     2017
#define IDC_REFRACTSC                   2018
#define IDC_MBRTRANSLATENCY             2019
#define IDC_LIGHTDIRBE                  2020
#define IDC_MBRTRANSDUR                 2021
#define IDD_CARDIO                      2021
#define IDC_LIGHTBOTH                   2022
#define IDD_TAB                         2022
#define IDC_MBRTRANSAMP                 2023
#define IDC_EDIT1                       2023
#define IDD_SIMPLECONTAINER             2023
#define IDC_SPRVOLINOUT                 2024
#define IDC_EDIT2                       2024
#define IDD_SCALAR                      2024
#define IDC_SPRMAXVOL                   2025
#define IDC_EDIT3                       2025
#define IDC_SPRLIFETIME                 2026
#define IDC_EDIT4                       2026
#define IDD_FOLDINGCONTAINER            2026
#define IDC_SPRFADEDUR                  2027
#define IDC_UPDATE                      2027
#define IDD_STRING                      2027
#define IDC_SPRSCALDUR                  2028
#define IDC_PICTURE                     2028
#define IDD_VECTOR                      2028
#define IDC_MEMBRANE_NUM                2029
#define IDC_DEBUG                       2029
#define IDD_SPLITTERCONTAINER           2029
#define IDC_TAU0                        2030
#define IDD_TOOLBAR                     2030
#define IDC_TAU1                        2031
#define IDB_BITMAP1                     2031
#define IDC_TAU2                        2032
#define IDD_COMBO                       2032
#define IDC_SPRREPULSE                  2033
#define IDD_COLOR                       2033
#define IDC_MBRTHRESH                   2034
#define IDD_BOOLEAN                     2034
#define IDC_MBRLATENCE                  2035
#define IDD_DIALOG1                     2035
#define IDD_BUTTON                      2035
#define IDC_MBRSPRFADESPEED             2036
#define IDD_LABEL                       2036
#define IDC_NXTMBR                      2037
#define IDC_PREVMBR                     2038
#define IDC_CHECK1                      2038
#define IDC_MBRTRANSLATENCY2            2039
#define IDC_SLAVE1                      2039
#define IDC_MBRTHRESHMAX                2040
#define IDC_SLAVE2                      2040
#define IDC_LISTLOGGING                 2040
#define IDC_NOACTIONTIMEOUT             2041
#define IDC_SLAVE3                      2041
#define IDC_PHASESPEED                  2042
#define IDC_SLAVE4                      2042
#define IDC_PHASEAMP                    2043
#define IDC_SLAVE5                      2043
#define IDC_PHASEFREQ                   2044
#define IDC_SLAVE6                      2044
#define IDC_MBRTAU                      2045
#define IDC_SLAVE7                      2045
#define IDC_CULLBACK                    2046
#define IDC_TRMINSZ                     2047
#define IDC_TRMAXSZ                     2048
#define IDC_TABCTRL                     2048
#define IDC_TRMINDENS                   2049
#define IDC_PICPIC                      2049
#define IDC_TRMAXDENS                   2050
#define IDC_TITLE                       2050
#define IDC_TRCOEFZ                     2051
#define IDC_TRNEARZ                     2051
#define IDC_SCALARVAL                   2051
#define IDC_SOCKFREQ                    2052
#define IDC_SLIDER1                     2052
#define IDC_TRFARZ                      2053
#define IDC_TRAMPY                      2054
#define IDC_PIC                         2054
#define IDC_TRFREQY                     2055
#define IDC_COMPX                       2055
#define IDC_MBRLATENCEFAR               2056
#define IDC_COMPY                       2056
#define IDC_COMPZ                       2057
#define IDC_COMPW                       2058
#define IDC_COMBO                       2061
#define IDC_COLOR                       2062
#define IDC_CHECK                       2063
#define IDC_BROWSEFILE                  2064
#define IDC_BUTTON1                     2065
#define IDC_BUTTON2                     2066
#define IDC_RICHEDIT22                  2067
#define IDS_HIDE                        5000
#define IDS_EXPAND                      5001
#define IDS_CONTRACT                    5002
#define IDB_BUTTON_IMAGES               5003
#define IDC_TABCTRLBAR                  5003
#define IDD_LOGLISTCTRL                 5004
#define IDC_URL_CODEJOCKEY              5005
#define IDS_COL_1                       5005
#define IDB_BTN_EXPLORER                5006
#define IDS_COL_2                       5006
#define IDB_BTN_ARROW                   5012
#define IDC_VSPLITBAR                   5015
#define IDC_HSPLITBAR                   5016
#define ID_FILE_EXIT                    32771
#define ID_PLUG_1                       32771
#define ID_POPUP_WELL                   32772
#define ID_PLUG_2                       32772
#define ID_POPUP_HELP                   32773
#define ID_PLUG_3                       32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2037
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         2068
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
